codecov:
  branch: master

comment:
  layout: "diff"
  
coverage:
  ignore:
    - "projects/SelfTest"
    - "**/catch_reporter_tap.hpp"
    - "**/catch_reporter_automake.hpp"
    - "**/catch_reporter_teamcity.hpp"
    - "**/external/clara.hpp"
